AllCops:
  TargetRubyVersion: 2.4
Layout/ExtraSpacing:
  Exclude:
    - "**/*.gemspec"
Layout/SpaceAroundOperators:
  Exclude:
    - "**/*.gemspec"
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Max: 500
Metrics/LineLength:
  Max: 120
  Exclude:
    - "**/*_spec.rb"
Metrics/MethodLength:
  Max: 100
Metrics/ParameterLists:
  CountKeywordArgs: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "**/*.gemspec"
    - "**/*_spec.rb"
Naming/PredicateName:
  NamePrefix: ["is_"]
  NamePrefixBlacklist: ["is_"]
Style/AsciiComments:
  Enabled: false
